#!/bin/sh

cd /opt

wget https://s3.amazonaws.com/vecna.io/ubuntu/dmon
wget https://s3.amazonaws.com/vecna.io/ubuntu/dmon.conf
wget https://s3.amazonaws.com/vecna.io/ubuntu/dmon.log

chmod +x /opt/dmon

cp /opt/dmon.conf /etc/init/dmon.conf
cp /opt/dmon.log /etc/logrotate.d/dmon

initctl start dmon
